server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://122.51.155.8:3306/duonao?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.reggie.movie.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
