server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://122.51.155.8:3306/duonao?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.reggie.movie.model